### ISSUE TITLE
Sliders Don't Work in Chrome with Strict Site Isolation

### ISSUE THREAD

**Issue by granthusbands** [observablehq/notebook-stdlib#5]
Following Spectre, it was recommended that users enable Strict Site Isolation in Chrome. Doing so makes all of the sliders in observablehq notebooks not interactive, with no indication as to why (and users will forget enabling it). Either a workaround or a notification would be great.

**Comment by mbostock** [comment]
This is a known issue that is fixed in Chrome 65:

> In some cases, clicking or scrolling on cross-site iframes may not work properly.  
> For example, this can happen when there is a partly transparent overlay above an iframe.  (This is fixed in Chrome 65.)

https://www.chromium.org/Home/chromium-security/site-isolation#TOC-Known-Issues

I don’t believe there’s any way for us to detect whether users have this experimental flag enabled. And, since this is an experimental flag and since the bug is fixed in the next major release of Chrome, we don’t plan on doing anything specific to address it. Sorry for the inconvenience.
