### ISSUE TITLE
Stdlib support for React.js / JSX

### ISSUE THREAD

**Issue by artyomtrityak** [observablehq/notebook-stdlib#62]
I would be happy to use JSX inside notebooks as a first class (meta)language.
ie
```
jsx`
function Button(props) {
   return <button className="btn" onClick={(e) => console.log("click")} />
}
`
```

I can submit PR if this looks as a valid proposal.

**Comment by mbostock** [comment]
This would require deeper integration than the standard library.

You can use the standalone version of Babel to transpile JSX, for example as shown here:

https://beta.observablehq.com/@mbostock/hello-jsx

However, this isn’t ideal because you have to enumerate the other cells that you reference (since the Observable parser doesn’t speak JSX).

It’d be better if we provided a transpilation hook, whereby the source that you write in a cell can pass through a function (also provided by your notebook) before being parsed by Observable and then evaluated. This way, we could provide a mechanism not just for transpiling JSX, but for many other languages (such as Markdown), without needing to use tagged template literals for everything.

**Comment by mbostock** [comment]
HTM is nice alternative to JSX that offers similar templating without needing a transpiler:

https://beta.observablehq.com/@mbostock/hello-htm

I’m going to close this issue as the existing template-literal approach is going to be as good as it gets until we support transpilation, and transpilation is a platform feature rather than something we can simply add to the standard library.
